Kolin jvm update
teamforus/me-android pull request #331
Opened 2024-12-10 20:04 UTC by maestrovsmaster

**Updated Kotlin version:** Upgraded the project’s Kotlin version from 1.3 to 1.9 to leverage modern language features, enhance compatibility with androidx libraries, and address potential runtime issues.

**Migrated to JVM 17:** Updated the project’s target JVM version to 17 to align with the latest Java standards and improve runtime performance and compatibility.

**Upgraded Android Gradle Plugin (AGP):** Updated AGP from version 8.5.0 to 8.7.1 for improved build performance, stability, and support for the latest Android tools and features.

2024-12-18 16:04 UTC, irinaBerendeeva87 requested changes
### Checked:
❌  error in log cat after opening  any transaction on me app and then closing by "X"

2024-12-18 16:53:49.341  1155-2156  InputDispatcher         system_server                        E  Window handle Window{5801427 u0 io.forus.me.staging/io.forus.me.android.presentation.view.screens.dashboard.DashboardActivity} has no registered input channel

2024-12-18 16:55:13.624  1155-1455  WindowManager           system_server                        E  win=Window{30bc9e1 u0 io.forus.me.staging/io.forus.me.android.presentation.view.screens.dashboard.DashboardActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1200 com.android.server.wm.AppWindowToken.destroySurfaces:1181 com.android.server.wm.WindowState.onExitAnimationDone:5030 com.android.server.wm.WindowStateAnimator.onAnimationFinished:284 com.android.server.wm.WindowState.onAnimationFinished:5471 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0$SurfaceAnimator:100 
<img width="1386" alt="Screenshot 2024-12-18 at 16 56 44" src="https://github.com/user-attachments/assets/fe7186dd-6c6b-4e84-ae01-a87d9d54bcf1" />

❌  button QR highlighted after open scanQR and then Close
![Screenshot_20241218-165800_Me](https://github.com/user-attachments/assets/71d2c1ed-fb75-4e21-9489-bb202b7a1ae6)
  
❌ no error when device doesn't have internet

https://github.com/user-attachments/assets/5bf38013-fad0-4b36-ba93-51f9f35fef27

❌ new transactions don't have title in transaction screen

✅
✅ no errors in the console
✅ error 422 and 429
✅ checked in different implementations

--------------------------
 
 **Not related to this PR**

2024-12-20 20:04 UTC, maestrovsmaster commented
### 1.  error in log cat after opening any transaction on me app and then closing by "X"**

**Impact:**

The issue is purely related to system logs and does not seem to affect the user experience. However, it may indicate a minor lifecycle management inconsistency that could lead to issues on some devices or under specific conditions.
Solution Implemented:
To handle this error gracefully, a try-catch block was added around the dismiss() method to ensure the application does not crash if the dialog is dismissed during an invalid state

**Recommendations:**

Monitor if this issue reoccurs or escalates in frequency on different devices or environments.
Test the dialog lifecycle behavior on low-memory devices or during rapid navigation events.

### 2. button QR highlighted after open scanQR and then Close

Fixed.

### 3. new transactions don't have title in transaction screen

The transaction item displays the product name, so when the product is absent, the field remains empty. It is possible to decide to display something else instead.

![image](https://github.com/user-attachments/assets/e59f7dd7-0463-4395-8f1f-3256441c5821)

### 4.  no error when device doesn't have internet

It's better to address this in a separate issue.

2024-12-23 14:05 UTC, irinaBerendeeva87 requested changes
Fixed:
- button QR highlighted after open scanQR and then Close

✅ yes new transactions don't have title in transaction screen if there is  "product":null

❌  Close button inactive while scanning qr


https://github.com/user-attachments/assets/9db88744-fd85-43db-a8e2-6b19db35bae9

2024-12-30 17:37 UTC, maestrovsmaster commented
@irinaBerendeeva87  @lexlog  "❌ Close button inactive while scanning qr" - The icon was removed because the alert dialog is dismissed using the Dismiss button.

2025-01-08 14:01 UTC, irinaBerendeeva87 approved these changes
### Checked:
✅ Close button 
✅ no errors in the console

2025-01-09 09:25 UTC, merged